name: 'Jacoco coverage report'
description: 'Comments on the PR for the jacoco coverage report'
inputs:
  github_token:
    required: true
  path:
    required: true
  coverage_path:
    required: true
  decrease_threshold:
    required: false
    default: '0.075'
  coveralls_url:
    required: false
    default: 'https://coveralls.io'
runs:
  using: 'node12'
  main: 'dist/index.js'
