name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Jacoco coverage check
        id: jacoco-coverage-report
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./fixtures/jacocoTestReport.xml
          coverage_path: ./fixtures/coverage-report-positive.cov
          decrease_threshold: 0.075
      - name: Check Jacoco coverage outputs
        env:
          REPORT_COVERAGE_STATUS: ${{ steps.jacoco-coverage-report.outputs.report-coverage-status }}
          REPORT_COVERAGE_SUMMARY: ${{ steps.jacoco-coverage-report.outputs.report-coverage-summary }}
        run: |
          if [[ ! REPORT_COVERAGE_STATUS ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_STATUS != "success" ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_SUMMARY ]]; then
            exit 1
          fi
          echo $REPORT_COVERAGE_STATUS
          echo $REPORT_COVERAGE_SUMMARY
          cat ./fixtures/coverage-report-positive.cov
      - name: Create Jacoco coverage missing target coverage check
        id: jacoco-coverage-report-missing
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./fixtures/jacocoTestReport.xml
          coverage_path: ./fixtures/coverage-report-missing.cov
          decrease_threshold: 0.075
      - name: Check Jacoco coverage outputs
        env:
          REPORT_COVERAGE_STATUS: ${{ steps.jacoco-coverage-report-missing.outputs.report-coverage-status }}
          REPORT_COVERAGE_SUMMARY: ${{ steps.jacoco-coverage-report-missing.outputs.report-coverage-summary }}
        run: |
          if [[ ! REPORT_COVERAGE_STATUS ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_STATUS != "success" ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_SUMMARY ]]; then
            exit 1
          fi
          echo $REPORT_COVERAGE_STATUS
          echo $REPORT_COVERAGE_SUMMARY
          cat ./fixtures/coverage-report-missing.cov
      - name: Create Jacoco coverage failure check
        id: jacoco-coverage-report-failure
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./fixtures/jacocoTestReport.xml
          coverage_path: ./fixtures/coverage-report-negative.cov
          decrease_threshold: 0.004
      - name: Check Jacoco coverage outputs
        env:
          REPORT_COVERAGE_STATUS: ${{ steps.jacoco-coverage-report-failure.outputs.report-coverage-status }}
          REPORT_COVERAGE_SUMMARY: ${{ steps.jacoco-coverage-report-failure.outputs.report-coverage-summary }}
        run: |
          if [[ ! REPORT_COVERAGE_STATUS ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_STATUS != "failure" ]]; then
            exit 1
          fi
          if [[ ! REPORT_COVERAGE_SUMMARY ]]; then
            exit 1
          fi
          echo $REPORT_COVERAGE_STATUS
          echo $REPORT_COVERAGE_SUMMARY
          cat ./fixtures/coverage-report-negative.cov
